apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "node-exporter"
        static_configs:
          - targets:
              - "192.168.86.12:9100"   # HomeLab5 (control-plane)
              - "192.168.86.8:9100"    # HomeLab1 (worker)
              - "192.168.86.14:9100"   # HomeLab7 (worker)
              - "192.168.86.10:9000"   # HomeLab3 (Docker)
              - "192.168.86.5:9100"    # SanxerPi

      - job_name: "cadvisor"
        static_configs:
          - targets:
              - "192.168.86.12:9001"   # HomeLab5
              - "192.168.86.8:9001"    # HomeLab1
              - "192.168.86.14:9001"   # HomeLab7
              - "192.168.86.10:9001"   # HomeLab3
