apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - soft
    - timeo=50
    - retrans=3
  nfs:
    server: 192.168.86.6
    path: /nfs/Kubernetes/monitoring/grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - soft
    - timeo=50
    - retrans=3
  nfs:
    server: 192.168.86.6
    path: /nfs/Kubernetes/monitoring/prometheus-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - soft
    - timeo=50
    - retrans=3
  nfs:
    server: 192.168.86.6
    path: /nfs/Kubernetes/monitoring/loki-config
