---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgCLmQRK/McpItngzTOyl1cQWnOv0KEjp5roXBu9bf3QzwhcYXojF3L3Wmp5ECK1XqtLR3grp4vbWdLk+3Kw3ZPu5haD4PF4X6a3WvJ2Ss+zDpkxjzcume8LTULKhLE8b4NXciIT3I67WIOFsmWgeV6hvD2giiSl38nvnu5eu1YPAowLQcpzeMRenGRKCgucoAro7gc0OTj9SHmpmsBY38WTkBvXZsXVX9Un11HUbrjHForPdBFLNJhv+gzGpr2YGSVZzWdHXBwyKKO2/vQuy3KZqmIIycDM6fnZBVclaqeiuV4ChuG2b7sneiqnhxsUqV0Jqyn8/GJs9hSVHRXb9aN/MrA3RzBBAaY0pwfZaIBV9/Y172gqV1g00b5vFK4WmFmWBdQ0e4xbTzYMREEcPu52nIE3meaWhQHERrBqkEHL7ESr56+NvRekhmGcQRxVdTkCCAc8qk8GEp3u8HGMcKpZbeISIE56F703awRLDYRImzBAf/CF8VHdNipYwkOiJ+zLDUnl6dV31v9LT/R0fcO+0xcnqhCxKTaElavAJwi6+2VgWwU9I/gbp15gFgygRMWvTpsL6iciPqOnOrUkrBkAp8yB3LOKVjsSCa+wt8KIvMf+JnotRG1v8zGGNpqmwf3WAJEPuh89XGLyfkLob7ItlIIG4sZAxFYuGtvmzji2RYbw3BmZJPgBzvmECER2jFCjqnH8DAf4z0i4l7/VrG23n4Q52g==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
    type: Opaque
