---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgAfTYezIwGQS0tHHd/ZpwLPWn1I0gzceCl3aYcS0LKA1U43yMEcukNqrPvQftooLP2tG9GR7WyfTp2hS9QHEqDwLwKGr8/Y49eCNg1ar7gVRpF0OOL6jf5UemNJyITzVUZjr9nly1JjP/+aOXo9Fg1Pn2fm0yGCycCEUz3X0r8Tsdrj/lna+KwV4VDXXV8Ax5QgVxBUvfKe9TWM9NYaJmiuESIiyW0fR6eHC46kr0L70+B64v51+dwVlA4Zwes4NqPquSppq2ldSu6GXIaAWZNxppnTaS6pWzRk5Sg1H7Fg8zaG2uEE+ZHMZqCIFVrtvS6DnJmP0UoYV58KjSpubSm9q513FPkcmeR7Gi0/wF0poXoyOu6vLGwGjDi+NkqF/9tzYNWgk3W2P9Auj72VKA39raDZe3DYCPhmbFdsUN9w1Xnrt31DtrGcpV5CdmKFZr6SOHz9H4xAf+yxZVC6rsyIfdeAsmr96RyCCP3qjt32hXMPdwJe99QKwvwsZO9QDztANjQOGWBed61kjMY7fBqFiLuXLrw36W8TOgX1GnbpQQRTftH1UAYJOpb/8Mhgwt51nYPzaqhquWOg3vCSsArGFqN4HRd2FJbRBqrLwd4N/LZn/xFfY2Z4Q2sjN/nOMmN5TUU3i8lKVIKlgD+MWzwhWA7GHMjDM9rIy6CXybHAHsy+QRmb3xLLEo4QEz2vOyYtD3dFnU657vRmKwkZTMrFuHCFik+Y7vvM26A/BttvYw==
    rootUser: AgBGcT4y75uPrXx+i3CCMkXikMhc6XeE+BfputuX/SQILYXtY+/8NJ+aEZKqJZKi0uc78WwKlHleoGmvn/U3sSgkXuDA+bKz5k5ZwtBVEfcD1eP7yYrf+kkMCNkZ4aB4IBNL12poXFrYcZ9RuWNiArhHyEant4l9jhr5q9etkDdXBrseM4aYUNO0y6ElGFwCQLH7xoPjIE1IpEdkbrVWIdfoE8tDyvpTuXv/bE6TG0JpUu8aM1qBG6rcBcSudzoO2ZeaTGNaVhpwsETxxbw1ROGnZl5+Wcru0FBKA2w0hgtkuf/zJsJVaqF+0N3UhxplIOP9V6/9t1c3+nCQc68uZNbXy3kxiTplC00HzQfX/+qEPpB/t8QpW6WJYtdP9Y+atdzCVai0Gm9x2CmS4EsucFFiiEmU0rS7/SxfMUwdSNQbHYKpRk9WbQlKTeAZajQSqU+ileJOZDuuDXtfnSk3L9yMKqZeSuigMtBp6sXxrV6t1bJkMoLZEyyHfEjxYgDPQ6c2Vs5ExPXgQNo+NE2lKtHhToJpi0hlOlgEBJgzfTKrQ81IJ7XRNn2TeiZuhe0IUzoJCUyEHd1u0VI3FQzFPD29xTNIUDnZHXpGBpa+PQyD52dDP03irS3ZhRtSZX5akInPOwtfz0J2GmCCEeWMYlEBy6ONlfcTxuAzZIRJEKaj7id0vpEUGFAsAmjerWiGio3w7pOH3fEJgrxE
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: minio
        meta.helm.sh/release-namespace: minio
      creationTimestamp: null
      labels:
        app: minio
        app.kubernetes.io/managed-by: Helm
        chart: minio-5.4.0
        heritage: Helm
        release: minio
      name: minio
      namespace: minio
    type: Opaque
