---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAFElcTndDjOL1iw4qRiLo9G8r63ZhHTKCg7b7Y9XLTqJlKNhCKdl2H2x0ErtSUXFFlMGHjLpxQKaaY2pOZW/7NklXU49vZt4X1jN5jukLsbPONkpb3I5IFyCk+8a/Qz30ttTgpCYKAwPOC2QgTFY4I1DlVWdr6m35BPO+t2P6H+k867A0+pvPBrCv9AcfrdydmyFdfabFm9ZmVUM6QzbU+qzhemH3QwqIYKuu7baFmem2NY1hKH14JPqFwAHgNTtZ88aymoSLAzyrguoP5Ofgk05/b/qQ+m9kgsOKWczFo37ryOB5zbHzzlGuhij+alPXxXYa7yzTFTGWaOXVRMjCOtPEI/6OPfhyrOL4FRS2BJXhPjHAqagF4dy7u3CPy6JqAb6Svtof6qAW32UVQXAIUkf4nIACATxfuLVn9AMN73cBfUPQsBc/M1mcqLTCkU5nQ+vcUyXfg313T+BFhFVTmheMmfCxT52WxF2WFvIM+xuKiFxrSocIyWSIqx2wQG3fl0K/lf3zjt9Mj1fxn3kG9GlnG85CqvjiQr2PZre0CHVpl86yIOJWheMMiNWjkZT5LCT82f9w8eqFjDHZWY+R/PCIYXmcixPwhAyVyD7G1d35IUU1cEimvEx/VoBQSbhndzMu7wQY/muTEjs+U9QAqGIhFfIFPYu97FRbwR9y/ccNXdvD8waFZzNI7eFZzHBHTqBzLvOXLHZ5/VAsuHgt20tsGnEFq7jAHTJDPhyWw6eYY9EiFeYBXktozMSqO7reU5RN4THEBztffQMZOlP/4UtIZ2RjLm7dTRv/Zo5DCbQjGGXvi8rQbMWqCeZI=
  template:
    metadata:
      creationTimestamp: null
      name: velero-credentials
      namespace: velero
