---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgAcizV/LhOxduaER6Uw9McDtu96MV+vkGgCGsgCoZMjyGrJOWw5fgQTUlgaShyeb39z6+NHZYVkj987oxMcbj2pQN5CSjgyv6xXketh7mx9N1jUoEA0f0yuK5NnbWHZYSZuyYchm8kRIRJY45TCqdx+ijz144NKZSBq51EtDK0bYBY4rSEWc1LinhhVNe6debNhz3kuDXgcV5PB3sYFn/5OVOWKFn4AfMiGTcB13OB1PAa6rxT+ZOt74idHuDXIUFH5sqZh3TAa3CgdCPMrdMnSzPUJnf15UQF4dNkTtOMC4jVPH+SEtlRWCLCl6bHy8ZCbLpBjVP3VNDkSGX4dw4/dXfXX7JBc7QZigEOlyXPpjcdl3kW6djKKqkw4xbBhM9NMugDuc1S4HW78959LkZ/r7mZ805WcM4oS4zIVMMPFjmsx5+PaFHXo6hR9fKnffA51A6a+NCeDRWJgJHFBL2gj+rR65A6Ki9ZKUjRunYsJ8IwNVTDOa6RFJaow+u/8AYtDDGXAqcuQAOUuS/9adzu+XIWltHqpSC3wyHdj4Zvi7oi9kHS1muU86DrueHU8uadkomOZmN+MIL85m8TT10fFD2ScyAxYf2aIO+On92Mo4mQovJU7HgRnOKfTZViC8y6EkHQd118LBDaY8Xc+MSPMy4GlId4/tV8kNY962xGFfb+/qF3kxQh2W4trqQgftHbpLgBV2IGahfQwFvCcwqSx6X+ukUy/w0o86yyUUzxz9Q==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secrets
      namespace: n8n
