apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data
  namespace: linkding
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: linkding-data-pv
  resources:
    requests:
      storage: 1Gi
