---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: linkding-secrets
  namespace: linkding
spec:
  encryptedData:
    LD_SUPERUSER_NAME: AgAXdvQt84dcNGPKnajoHrtK71TvDgzZc/qtgIcewDR6xFXaHvTaKDXeB1T7zbGkT+6BK/IfrRtYvMvrlxKoZJZr6T+/sn6HSyMWvs9kKKMxIE6odu7SDQagiAF+yS7o6pyLaodAJcqkUY91fYZuyYygbpMPmY0amLmyVCltl7VXPccIMew5ylGXWToG6Ky/kgUutMmIQy+HTGKbToVUxn27Hi9AasvkyqPQs6LGv9MPkPO2hotAwRz7AYPiQf1HRyQISur1oZJOqFzYSJAuz8NdJGd1Wppmkl7ef9ijgvLn8oaRk/Ap4HJqV2JCTyW3D1jeByY4DdTvOcXsaJ6oU8hVVdxbW8AYQAgAGJjtQemuklg6gHURSWx4RdJOSvaAzDa/8XgouiWjMBS3hn/MpCJgYLSVdcHuhUClaQqLt3V/Ce9KkbrwlJo2wZtQrtq96MpRYQdJCAkDbWtDU6zY7h8o6jcHUItcspIPSlwoVXRlbs1SPSbeuUJw3e3H47vPVqwQj8Qh+H63NhauLrtBKApQV6Z4c52ezsb2d4shdVpKbmnUHuY2ycR1HnLNBzQFxDX6DS1GnexRA0ycsKbEbW2l2n5YR06YAtKUa2uSEtzJfe9oqcsL0ZYN7WmNw8dM4oGm/LVXK3PTQV0wVEBHLlXJtRLZkNvjByqEj0xdj/S+Q/eJDJpdFPiFeMTn/DEMpcQdtIxxWA==
    LD_SUPERUSER_PASSWORD: AgChlE3B4O1aeNYRF3bscIYV3U0ovp2EZLORe0Mddv014YeLnOCSN/6PyWh+z9jaSBtI9WYeVeuTUFJl0rkyyknBHKiHy8sBGGbS4VICTvOyViqUgkmnHOGnGZghDDpCzViC1qKdcXrqseL6ILZNOuSZCHu8EmsSs5tuC0VOLVaoKMN5nB7LF2nDhAvkYw+6uuo8nRdnuAYpyIqKLttm8Ha15oLIasAHcOWQWpowEg4a3+GwOzsE23eLsMR8FOONDRsybTaQPxoG/bph6xfJZtocKlwoSNTD0CQ7lztJ0Y/hmTip/JA4lm4zlAu/WkenpNjs2VPtiKgZLNdyhf3eQC2WE+5FWYPaK4a95+XWRom6WwwxQh3scq+JjzyDV4a4v5/nMChQgMc6oWMTzPi5shiX5SqCNk7CSkNz7GvEDFEGYUPoZTHcsTMw2gJIE/qLdoPRNGiqhZjoLVsvCE5oEOw9xVthvnKhsgs2jVnhMoGrdrgtlZ3HBUn/FKqDVB0vzsiB00DqW2XVjrZ2Irine/ENTXHKv2rAfNiNzMDNnAI7OBNYxEVOYUFBnqoVpZ2EU+Z3emuSAYPDwcRxWK9Id10DdKFuEiJt+PXp0l2kGVqvKYBsAtODJy/iaUT5Vj+ZVO3Dt/TB/pBnU42Uje9e+6U7+1cYJXHa5iyCdetip7ytqGw1lEhkx1DoNFZssLgt4uNTOd0p6/llhqPTRtcUuw==
  template:
    metadata:
      creationTimestamp: null
      name: linkding-secrets
      namespace: linkding
    type: Opaque
