kubectl:
  image:
    tag: "1.32"
credentials:
  useSecret: true
  existingSecret: velero-credentials
configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      config:
        region: minio
        s3ForcePathStyle: true
        s3Url: http://minio.minio.svc.cluster.local:9000
  volumeSnapshotLocation: []
snapshotsEnabled: false
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.11.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
