apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-db-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-redis-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
