apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      enableServiceLinks: false
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          ports:
            - containerPort: 8000
          env:
            - name: PAPERLESS_REDIS
              value: redis://paperless-redis:6379
            - name: PAPERLESS_DBHOST
              value: paperless-db
            - name: PAPERLESS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets
                  key: POSTGRES_USER
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets
                  key: POSTGRES_PASSWORD
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets
                  key: PAPERLESS_SECRET_KEY
            - name: PAPERLESS_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets
                  key: PAPERLESS_ADMIN_USER
            - name: PAPERLESS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets
                  key: PAPERLESS_ADMIN_PASSWORD
            - name: PAPERLESS_TIME_ZONE
              value: Europe/Copenhagen
            - name: PAPERLESS_TASK_WORKERS
              value: "2"
            - name: PAPERLESS_THREADS_PER_WORKER
              value: "2"
            - name: PAPERLESS_URL
              value: https://paperless.sanxer.dk
            - name: PAPERLESS_CSRF_TRUSTED_ORIGINS
              value: https://paperless.sanxer.dk
            - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
              value: "true"
            - name: PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME
              value: HTTP_REMOTE_USER
            - name: PAPERLESS_LOGOUT_REDIRECT_URL
              value: https://auth1.sanxer.dk/logout
            - name: PAPERLESS_CONSUMER_POLLING_RETRY_COUNT
              value: "5"
            - name: PAPERLESS_CONSUMER_RECURSIVE
              value: "true"
            - name: USERMAP_UID
              value: "1000"
            - name: USERMAP_GID
              value: "1000"
          volumeMounts:
            - name: data
              mountPath: /usr/src/paperless/data
              subPath: data
            - name: data
              mountPath: /usr/src/paperless/media
              subPath: media
            - name: data
              mountPath: /usr/src/paperless/export
              subPath: export
            - name: data
              mountPath: /usr/src/paperless/consume
              subPath: consume
          resources:
            limits:
              memory: 1Gi
              cpu: "2"
            requests:
              memory: 256Mi
              cpu: "10m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - SETGID
                - SETUID
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: paperless-data
