apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-redis
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-redis
  template:
    metadata:
      labels:
        app: paperless-redis
    spec:
      enableServiceLinks: false
      containers:
        - name: redis
          image: valkey/valkey:9-alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: 128Mi
              cpu: "250m"
            requests:
              memory: 64Mi
              cpu: "10m"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: paperless-redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-redis
  namespace: paperless
spec:
  selector:
    app: paperless-redis
  ports:
    - port: 6379
      targetPort: 6379
