apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-sanxer-dk-tls
  namespace: longhorn-system
spec:
  secretName: longhorn-sanxer-dk-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - longhorn.sanxer.dk
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.sanxer.dk`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: longhorn-sanxer-dk-tls
