apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@gitea.sanxer.dk:2222/admin/Kubernetes.git
    targetRevision: HEAD
    path: apps/vikunja
  destination:
    server: https://kubernetes.default.svc
    namespace: vikunja
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
