apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-db-data
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
