---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vikunja-secrets
  namespace: vikunja
spec:
  encryptedData:
    VIKUNJA_DB_PASSWORD: AgBQHs1lCsn7xgyEEGXM6mq/2Lrt5iev7O21oWcpNZ+2EkPfl59tRG89hwQ7olOdbQ+M5EIMGqrRKE/bM85TT0AybcDhBLGgFGGKFFuKNJIro4igwAjUTpZkf0ylaUCKURGYt6UQb7GdGu9UFb97G9PXdjNKBpRKpzlDmEcmC+gmLrryi0FwdILEsUfyPr1EzJVMmjgMBPQ5VP3b3mPLym2M4QlAg+dkr0eb70kmj2BBPFq1YetjEaEXfKnNEoYCbSmoBsz7UQlF18ANZioqU4yttgfEU7D8IwFYpEX+sZj8o7ZoBj5kub4BjYW4VGm4wbRu5BI6mSUt/JTFEktf1NsMAHqkDTjSKChiEbZBeB0G4gmBnYZFWedQmCTiVzEpojbrbyCZFjQxj7D6XB2RRYsByVOsZxehxhX/TVK2/c7ldXeoBUW4SlC5reIUvklZWQ3MO3fg8lNrVqS+svno+N3k23p/LyP5Vw2gcwIpK2XY5toPnX6FAoq1VdguCF7FupHYcjXUPwqmlRXHz6yg4hr8sV5wiWi5VvU95or4QV7kebdWYkrYb/INd4i5Qvm06XsMekLxr/SRauUoObYRRrBNsOvfFGpPTfJEgqW/j+AwT31/DW87wpnZSrPDlQABLET8lu8mTtxsK2KNq55RzQiFLik8v7vllndsC1lhjUutnu75GPDJx8kI7XLdQI3+1cw/9S6hhJR5n7BbQzb0GCEWdxF2LH4IfoQfztCytNCqCAs8diTSLoBSSl+PYRCUWCKZmtDN3PYtgHEeplEF56wy
    VIKUNJA_JWT_SECRET: AgAR1s/A1YgEhOma0GF6OPcUNoIAt9tIU9Wf7I/y8u6gKm5yJEOrVfrEE5mYUcfGaevEUtMKoQbEqp+NLvKXqxfUYReJOJV5N4JUCEZzVPKU/rda70HT5F9SidLnJmqMrg+LnH3che6OujD1YyJUXVDctvtIglS39VTCnHUy8iSIe/q+NftZ5w1te1JkWszX/znStS0kXrvSe9Aj/1mfVK7nynjDUJUr/egRH7R2dSstzfWB7WJIHkOlOCVWBKruFA7P4d3GpqxnptgpTUCoAF8Sbe/G2zORvRQ5+7neldGM6kAPXD83FopnsJI0K9q7G8abFV9HD8o+vbcimsg0Mvy2d+6BZhMYa9PBmH7SM5KrzYREoxzasJBzSgaDq2OinJx/RsITSqG+vOtG7zDONJgCVxlK7ORUTOUu9zk3Ui132WSJOlUUy+adjyWrP5oXc4OWN0heAwymH/C5BOJCpFhrvExwxIDAnCy0+bgCz4yYYZiYPECvNjVCegKHW8Rsw7xW1lCFC3iBXt88OLKt4ACW67thwUHUB/yhOEVesY141tBTkN09O0MS4HZOdNx3I/0qtDbpRXQvYQfRx/b9v+smsCOCn111wH+Amw26KZD/iBgddj6t72B0txyiMG8trsnvTYQom9rEXph77P0DmfI3B7lcG5j1xDdPxDHUH2cETDIiYsmSOU7YYOS2vIfIiq45eWVuEA62Bp2tM4srR444BBIlczbqAbaYIhJ5A2rqYlBjpkbBUhaOGJ1whgbqAl2VR4BBLrN+3zIiBXuBIauq
  template:
    metadata:
      creationTimestamp: null
      name: vikunja-secrets
      namespace: vikunja
    type: Opaque
