apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-upload-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - soft
    - timeo=50
    - retrans=3
  nfs:
    server: 192.168.86.6
    path: /nfs/Pictures/immich-upload
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pictures-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - soft
    - timeo=50
    - retrans=3
  nfs:
    server: 192.168.86.6
    path: /nfs/Pictures/Pictures
