apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: immich-upload-pv
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pictures
  namespace: immich
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: immich-pictures-pv
  resources:
    requests:
      storage: 100Gi
