---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: filebrowser-secrets
  namespace: filebrowser
spec:
  encryptedData:
    FILEBROWSER_ADMIN_PASSWORD: AgAWn9KQWC/1tJbFEuN2UMxQXrYVE6KzrOc1hD6Z8V7MtkIvQttjwQuzIzdg8aJqfZTzDFEc1Tyb4S5PqRxiBFdH5y210junh11jKKV8e7eT3AlgJEaqaTUDqKzql6a1djM3+ploxxWvIWlbc+62JUWKzsnEiwL9lDykIKq0vHEuqtM6cgc7rsNtW2ZegR/JHaSgc5PH1G1tZnnfbV7vnIEieT9JWzzHrk9io0E4rP3WUDN5f4EyxceMrfqd/AI3ZIPFJTBM80JPNtL7pJm/S46EdlM/owbqZwOkPy+AQR7pihi+epa15aglFHnj4NPZnPzD9J747dK9qzGP4zijZ01vSgfrgH4q0neBgvzF9xra7Fs0GizPZko4Mz6e8NtGsmNowxLYr2XxOzjQ7gDZJidtL6VvPWo3l41r2vYkWwq6KkDbPhTDufgjEYN327jhO9kwZ1JmyXDJGUVDoseuqozPss0fuP8is3LfrRsNl8ka89r60mmHzPaLT3LEdlPXeOVRVRpYgDdDD/UdV561zzlKuCOP7rGsa+OFREiYk9hf/vjca9hhby0cZiklT/AjHWx0UNacldw7vZz5OaAyLPjcbzEd6VAnWj6Q0OFWshZR3igxRjEBHVx4NQjl+4wfuGXboLeyHmHPdt1BcL+9PZP6Qj6uHiuIykFcTYP8UVl8ILbQiuX1RSQNtTujpODleZsmljcPoVsqDDjumV15jEXXaaxYtw==
  template:
    metadata:
      creationTimestamp: null
      name: filebrowser-secrets
      namespace: filebrowser
    type: Opaque
