---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: trufflehog-secrets
  namespace: trufflehog
spec:
  encryptedData:
    GITEA_TOKEN: AgBf2zrlZtxF1TYQ2h3SAsFFF4MCCAo7MH1+aLRG1s3Dv1UoU4Ec31BlFg7rM3KUkmjBNksoNMKSuwF9T4sQWxLi3sQ0sIvD9cPSuJOLb7Ce1Ais93kuEmn6lfQNXzn+dTywAWtZgQn8qyTlWzXF10wqUpgSdltqMMMMV3RWBFqY1TC2ru0GlMz0yh5g0D+vjO6qh8rhsr6qNEmS1Ts7+y44Li4E/5bAKYamXQr0oHLedQK0DkKed/d6QPFDVpLFTHU24fhOKSYCULH5g2U8q6T9tIM9NF1npwp42ygCulltVGWip2anTG/BMQ/+1Evtbeqd+/ivlWFGy0K+iLIF8u8stezVPCfhWPxbS+KrwecBADj1q1/KFMtXz1OSzplL+BGJXbKzM8CJgorCme3PBTorLPIn7YIQGVANPBV6/8haMxdXm8utIJTSnyg1i7VcPaGMm8DPvVDv8LVdkvtLttTWnqVYYC1yG6nNazZsZg/6YEcU2NFkyl0TdyTvcFxDlXyiF48Yj5thGGPqNzVXWbBeRGNBwlEqIDVFL+X9jiL1+EKurTLLDzs6sxcLCvIvk8ASG2qyPsw7EuC4RJQiJAVvGdHdQahXA5WivVY5nwM3pwAzY1t6P0cDOuQGdgdKUWquDEcusMt5SObkFkcHHflUuIsAbiEKkv3SljnevsLjB45i16BCjIAlrHk9MN8RbQwbMgnSPj9Z4oKv9akqM4JGaztx8ejIeqv/nXZAoiDZe7qxIdJavS6i
  template:
    metadata:
      creationTimestamp: null
      name: trufflehog-secrets
      namespace: trufflehog
