apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-config
  namespace: netbox
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: netbox-config-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media
  namespace: netbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: netbox-media-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-db-data
  namespace: netbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
