apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-data
  namespace: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: wallabag-data-pv
  resources:
    requests:
      storage: 1Gi
