---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wallabag-secrets
  namespace: wallabag
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCbon6Qmos+myivoBu0HzDxz3ioNKFTuOwiYcYSLokonWaPb4gIhagmdXU8AR7xnwUicpBCoA6IQahGDc1XxPkUWf+jJKFZG3oY8WmQwgu2SXuQiz2DGRAh/m1eDzRUoOP3UX/3IN4unzBmRUI+UelaPx5oE8AbAy3Xobwe1ZvQx2MQzERzkJrxH/JOuxvmLdwIfXuscqglM73RK+/aALzhZSUdvQixjF3LF5aSl2zeXf/bNv0JQ9+rIPmxDJJK4ZfKXGBZZE3foZ3wsE4DL+Vx/vCNc0rAgw8JTgan94XzOh6zeqLFCqoDlHCjl1P/HKv8hIe5jNBTj1RB81ASM1Y/547Udmk62JNC3CTRLkgQZ92n6PYPL+y8iPPWetIWqFm6BOjAPP55gBWMZq70WGG8sfDy/3We/YAIZYPfDn22aPc0CPrulMMVc04n2XqUv0CI1dnhrfecSoCtqa/HTsHF0mPr0HWDfdetsup4EZlMNDkHVpgQ2a32TWugLEvQHXsj0UHIURCTrchTJzEGQSj7XX0GhJQ6Vshzy2ZfURHUNCJUKFLjA6jbckJhCLmy03VlkcWH74wjODgxne/wIanOHhO7JPRe+1Fc7bMUHD7vB/brJkPrex1EXpIyof+y2VzRvL1jbhjgOLo/94yiqXMDr/oTpWeF0K/WCIs5DdV7C0TxWB27MBzcV2uuULqr6CbT921dtJ8a6t5mboBAUBQ8NiufomrNrCUpo2hlK1Xp3rB0qCUdx+GBuyyLO6BnKdE=
    WALLABAG_DB_PASSWORD: AgAdFFXX2wtG7IkuABBh2iz/IwQ0zzB/slEAZ1vwryOl9+KLhA9hPatJpVhI6D/jhK8UnUlSzVf7nBMCZ5g04pg/rB/MSDbYQaWYwEUYPg7jSCQ77m46VtfQyzDvAssQVkKFhY3dyWCb0LBuP237ZJMGRGfAXZ71nMXF+xrgRkygC0VfU0ikrBnBFJOUef5kdILirrYWZX89awo0ls9S7fR6mYSwD64TwIlVgbLYrG57YoRv8oVJGesD4QmN8LO5Tub78dT1eTV645JH6UgNuyfUNYpaWA8KqyMztJYYc5bJ8VqBNB7DG6GyZXNiTNLw7uB9d4eceTO2BofzSwHQPK9EJN0jgHhWA+4XH9TGSAisLaxSUGU3SSZpjTucctTTupNNEnvEg79xzh6V56qxHbQ7weGRHgukfP8HLd5uKxrmQOaZbi9TpQ2ZXnG3AnzUgScT4P3aLCZTGQT6F67Efiy+hHjcjxSYVD3tbeKhtHJAzMm7gK0b1wuobpuHY8ud2cKpL+398D9HgAWkk4Rcwv572nvEuT70NHrlHx0TwEyGtYZX/T152ve2SNWGTjESOZM6HxUc3aNb+ObY/nIOHU9OZMwPTaCkYaaH2T0vocYoH/V7X/5nE19vxLfXmsgmxD8ru/dEikc6ly5vinJ+lVzmJjPXmREgv90JhN++82/IamIrJFbQ1LwrBjkpjoEBqWME1P0ZzQuOS5d8l3pp1nLu6nPl7s8QIaMW95wyuEe7h9hNiWwO6DNwxPgI4Kn7SE0=
  template:
    metadata:
      creationTimestamp: null
      name: wallabag-secrets
      namespace: wallabag
    type: Opaque
