apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@gitea.sanxer.dk:2222/admin/Kubernetes.git
    targetRevision: HEAD
    path: apps/syncthing
  destination:
    server: https://kubernetes.default.svc
    namespace: syncthing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
