apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-config
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: freshrss-config-pv
  resources:
    requests:
      storage: 1Gi
