apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  selector:
    app: gitea
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
spec:
  selector:
    app: gitea
  type: NodePort
  ports:
    - name: ssh
      port: 2222
      targetPort: 2222
      nodePort: 32222
